module.exports = {
  CLEAR_ERROR: "notifications/CLEAR_ERROR",
  CLEAR_DATA: "notifications/CLEAR_DATA",
  GET_ALL_NOTIFICATIONS_REQUEST: "notifications/GET_ALL_NOTIFICATIONS_REQUEST",
  GET_ALL_NOTIFICATIONS_ERROR: "notifications/GET_ALL_NOTIFICATIONS_ERROR",
  GET_ALL_NOTIFICATIONS_SUCCESS: "notifications/GET_ALL_NOTIFICATIONS_SUCCESS",
  UPDATE_NOTIFICATION_REQUEST: "notifications/UPDATE_NOTIFICATION_REQUEST",
  UPDATE_NOTIFICATION_ERROR: "notifications/UPDATE_NOTIFICATION_ERROR",
  UPDATE_NOTIFICATION_SUCCESS: "notifications/UPDATE_NOTIFICATION_SUCCESS",
  DELETE_NOTIFICATION_REQUEST: "notifications/DELETE_NOTIFICATION_REQUEST",
  DELETE_NOTIFICATION_ERROR: "notifications/DELETE_NOTIFICATION_ERROR",
  DELETE_NOTIFICATION_SUCCESS: "notifications/DELETE_NOTIFICATION_SUCCESS",
  ADD_NEW_NOTIFICATION_SUCCESS: "notifications/ADD_NEW_NOTIFICATION_SUCCESS",
};
