module.exports = {
  CLEAR: "config/CLEAR",
  GET_SYSTEM_CONFIG_REQUEST: "config/GET_SYSTEM_CONFIG_REQUEST",
  GET_SYSTEM_CONFIG_ERROR: "config/GET_SYSTEM_CONFIG_ERROR",
  GET_SYSTEM_CONFIG_SUCCESS: "config/GET_SYSTEM_CONFIG_SUCCESS",

}