module.exports = {
  GET_DASHBOARD_INFO_REQUEST: "dashboard/GET_DASHBOARD_INFO_REQUEST",
  GET_DASHBOARD_INFO_ERROR: "dashboard/GET_DASHBOARD_INFO_ERROR",
  GET_DASHBOARD_INFO_SUCCESS: "dashboard/GET_DASHBOARD_INFO_SUCCESS",
  GET_REFRESH_TOKEN_REQUEST: "dashboard/GET_REFRESH_TOKEN_REQUEST",
  GET_REFRESH_TOKEN_ERROR: "dashboard/GET_REFRESH_TOKEN_ERROR",
  GET_REFRESH_TOKEN_SUCCESS: "dashboard/GET_REFRESH_TOKEN_SUCCESS",
};
