module.exports = {
  CLEAR_ERROR: "security/CLEAR_ERROR",
  CLEAR_DATA: "security/CLEAR_DATA",
  CONFIRM_PIN_REQUEST: "security/CONFIRM_PIN_REQUEST",
  CONFIRM_PIN_ERROR: "security/CONFIRM_PIN_ERROR",
  CONFIRM_PIN_SUCCESS: "security/CONFIRM_PIN_SUCCESS",
  CHANGE_PASSWORD_REQUEST: "security/CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_ERROR: "security/CHANGE_PASSWORD_ERROR",
  CHANGE_PASSWORD_SUCCESS: "security/CHANGE_PASSWORD_SUCCESS",
}